//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.Scorecards = new HashSet<Scorecard>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string NickName { get; set; }
    
        public virtual ICollection<Scorecard> Scorecards { get; set; }
    }
}
