//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int Id { get; set; }
        public int ScorecardId { get; set; }
        public Nullable<int> Strokes { get; set; }
        public Nullable<int> Score1 { get; set; }
    
        public virtual Scorecard Scorecard { get; set; }
    }
}
